[package]
name = "cbor"
version = "0.1.0"
authors = ["Hans Larsen <hans@larsen.online>"]
edition = "2018"

[dependencies]
half = { version = "1.4.1", optional = true }

[features]
half_float = ["half"]
std = []
default = ["std"]
